language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "wenhao"
    token:
      secure: "mDl/xgERgg3ruU3+PZizVKhuBTlouTxwhJ4OE8+t1xuvtnME+qQYebdQ2FezQqFK4ZP3WzzwdcVWOWFUP7hEy3MR7P4ldDNnb8VUhfssbz4d1+jYXujJ7F446KeoOw8fqFY7rTqqiLD5LD4IrQ1969jc6hcjdrDkOKTwQt/AZrLI3y4+TY0ATPa5lrzXA/oD0nWQn5rbP5GZuu16evnI5+SCC6LWb7Hr9Fb7PuwPIr4zesZ+S7JH+S32GdqwZ+tvWX4s7igalSWtNS9gjem+YDiw7dnXX07ZHG1iLTmopZpn/WAVZvt6RpNkgaCFSSavAXPVxmxHXo09ITxUoHTZgz9tLILb9UbrikuqFDtobLDt3TEEa61gizQ/Z7tHMk1vIPcIsI7LHtnZFfZ1hrYpvz1YakelpexIS4qxZ5KY+xcPBSDnimX6dPagvUiDLzTKI615ENl5Bd3Qa1r1QK1sn7ikuyaruWffOssEO4Hwg85Y0ARvHGI4qgDfao8bX/XiLtuweKll9w11SGr5IsaNrRDgnjToCHht++DXI16SVRTaH2pV5EEBAPQGWluIPZx9xHGc8q69D6sn+1xLvm6syqcG45daKVqReEps1wPCai+x2MYNcLQHAFeLDnwyV3Sq7xvz0lmwWusZjaUQKw1ezVoCqkG8I6DCMNj2rIU0fvE="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check sonarqube -i

after_success:
  - bash <(curl -s https://codecov.io/bash)