language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "wenhao"
    token:
      secure: "DpJByYWdDOqSnMhgOy1SWgUKNZIE36Mm7AyicXPcNLJkmELREFgB1SzxXwvP6I12CXxPJNlTibKt6bZLFTVT0ZM3rebwCVCksSr0RYWB54/P3Ot69jcwzLOegNkQLwJO9Z0yDHSjW9iQJohnpGjgpx4UNoqEcL7WLnmBPvatCP9JXFLmfdfSZH9bn8DC7ovo1SetbL+fPontEdmO4nnDeBLeNvqQnhYXxyqkRg5VJScxkctryP48kZowq9PTE2BLrs2ldA+i2QMIw2F4lbuApyXBlaeeoFNMqaDdTg8pJtXBPElvm/4vDyhyjxM50gknL9aBjxubNdgtfeSDLgVuWho/eVUjsPctjkdXeTWt+OZLoc3nfgo1huiNZDFf19THPjGA+jKm9CtaNz8TXrezaL8OObOG4Q/4pnCDfaMXldG/p+P2VREp6B+aAfL32OAhpK9MSzSVrLYgUaEpz17ISUdzoy4fMHldzeyQBYC6z89JKyz2EfTsOFL41pcr6Bf0ZeCdP5Sei11/pZsN/fi8lLkNYO+5fqe1B6ISiq9bGEvHtU/0+T/OKvAShNxQqtzUO6IFQYuKSM4uNiCz6MtmsNWM96x/Gzu5gcERfvjsaoYmpHKoouH1k+JRpmaBhGOi2fAuj4aKJBHJGmPaf0LoJzQ0rsXmR8goy45n2r6QIY4="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check sonarqube -i

after_success:
  - bash <(curl -s https://codecov.io/bash)